### ISSUE TITLE
Request: A way to save a build and stats?

### ISSUE THREAD

**Issue by annerajb** [ununseptium/skill-calculator#20]
Would it be possible to make a export/share/save button?

**Comment by ununseptium** [comment]
**Hi annerajb**
and thanks for your feature request.

The request you made is a really popular one and it's also the highest priority right now.
Unfortunately i don't have enough time nor motivation to work on the skill calculator right now.

The issue i am having with this feature besides the time and motivation has a technical background, since the app is not persistent when switching the tabs which causes some weird and critical behavior. 

But i already have a solution in the pipeline which would make it easy to implement the feature you requested. 

Last but not least, i won't promise something nor will i set a deadline on that but i'm working on it (at least in my head) and someday in the future the feature will be released ;)


Best Regards,
Tim

**Comment by ununseptium** [comment]
#18
